USE ecommerce_project;
-- 1. What is the total revenue generated so far? 
SELECT SUM(revenue) as total_revenue FROM sales;
-- 2. Which product category has sold the most units? 
SELECT CATEGORY ,SUM(quantity) as units FROM sales GROUP BY category ORDER BY units desc LIMIT 1;
-- 3. List the top 5 customers by total amount spent. 
SELECT c.customer_id, c.customer_name, SUM(s.quantity*s.unit_price) AS total_spent
FROM customers AS c INNER JOIN sales AS s ON c.customer_id = s.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 5;
-- 4. Which sellers have generated more than a set revenue threshold? (HAVING) 
SELECT c.customer_id,c.customer_name ,SUM(s.revenue) as revenue 
FROM customers AS c INNER JOIN sales AS s ON c.customer_id = s.customer_id
GROUP BY c.customer_id, c.customer_name 
HAVING revenue>5000 ORDER BY revenue;
-- 5. What is the average order value per city? 
SELECT c.city ,SUM(s.revenue) as revenue 
FROM customers AS c INNER JOIN sales AS s ON c.customer_id = s.customer_id
GROUP BY city
ORDER BY revenue desc;
-- 6. How many orders did each payment type handle, and what's the average payment value per type? 
SELECT payment_type, COUNT(*) AS number_of_orders, AVG(quantity * unit_price) AS avg_payment
FROM sales GROUP BY payment_type
ORDER BY number_of_orders DESC;

-- 1. Find total revenue generated by each city.
SELECT c.city, SUM(s.revenue) AS total_revenue
FROM customers AS c JOIN sales AS s ON c.customer_id = s.customer_id
GROUP BY c.city ORDER BY total_revenue DESC;
 -- 2. List categories along with total quantity sold.
SELECT category, SUM(quantity) AS total_quantity
FROM sales GROUP BY category ORDER BY total_quantity DESC;
 -- 3. Find the number of orders placed by each customer.
SELECT customer_id, COUNT(*) AS order_count
FROM sales GROUP BY customer_id ORDER BY order_count DESC;
 -- 4. Display average unit price per category.
SELECT category, AVG(unit_price) AS avg_unit_price
FROM sales GROUP BY category;
 -- 5. Find the top 3 categories by revenue.
SELECT category, SUM(revenue) AS total_revenue
FROM sales GROUP BY category ORDER BY total_revenue DESC
LIMIT 3;
 -- 6. List customers who have placed more than 3 orders.
SELECT customer_id, COUNT(*) AS order_count FROM sales GROUP BY customer_id
HAVING COUNT(*) > 3;
 -- 7. Find total revenue per payment type.
SELECT payment_type, SUM(revenue) AS total_revenue
FROM sales GROUP BY payment_type ORDER BY total_revenue DESC;
-- 9. Find the customer with the maximum single order value.
SELECT customer_id, order_id, revenue
FROM sales ORDER BY revenue DESC LIMIT 1;
 -- 10. List all orders along with customer name using JOIN.
SELECT s.order_id, c.customer_name, s.product_name, s.revenue
FROM sales AS s JOIN customers AS c ON s.customer_id = c.customer_id;
 -- 11. Find cities with more than 10 customers.
SELECT city, COUNT(*) AS customer_count
FROM customers GROUP BY city HAVING COUNT(*) > 10;
 -- 12. Display the number of orders per status.
SELECT status, COUNT(*) AS order_count FROM sales GROUP BY status;
 -- 13. Find the average quantity ordered per payment type.
SELECT payment_type, AVG(quantity) AS avg_quantity
FROM sales GROUP BY payment_type;
 -- 14. List top 5 products by quantity sold.
SELECT product_name, SUM(quantity) AS total_quantity
FROM sales GROUP BY product_name ORDER BY total_quantity DESC
LIMIT 5;
 -- 15. Find customers who haven't placed any orders (LEFT JOIN).
SELECT c.customer_id, c.customer_name
FROM customers AS c LEFT JOIN sales AS s ON c.customer_id = s.customer_id WHERE s.order_id IS NULL;
 -- 16. Display total revenue and order count for each year.
SELECT YEAR(order_date) AS year, COUNT(*) AS order_count, SUM(revenue) AS total_revenue
FROM sales GROUP BY YEAR(order_date) ORDER BY year;
 -- 17. Find the second highest revenue-generating product.
SELECT product_name, SUM(revenue) AS total_revenue
FROM sales GROUP BY product_name ORDER BY total_revenue DESC
LIMIT 1 OFFSET 1;
 -- 18. List all orders with revenue above the average revenue.
SELECT * FROM sales WHERE revenue > (SELECT AVG(revenue) FROM sales);
 -- 19. Find customers who spent more than ₹10,000 in total.
SELECT c.customer_id, c.customer_name, SUM(s.revenue) AS total_spent
FROM customers AS c JOIN sales AS s ON c.customer_id = s.customer_id
GROUP BY c.customer_id, c.customer_name HAVING SUM(s.revenue) > 10000;
 -- 20. Display category-wise average revenue per order.
SELECT category, AVG(revenue) AS avg_order_revenue
FROM sales GROUP BY category ORDER BY avg_order_revenue DESC;
